---
- name: Configure GRE Tunnel source 
  template:
    src: tunnel_source.j2
    dest: "{{ path_file_gre }}"

- name: Set launch rights
  file: 
    path: "{{ path_file_gre }}"
    state: file 
    mode: +x

- name: Adding a script to the startup
  shell:  |
    echo "post up {{ path_file_gre }}"  >> /etc/network/interfaces

- name: Tunnel GRE UP
  command: sh {{ path_file_gre }}